### ISSUE TITLE
Question around `.down.sql` migrations

### ISSUE THREAD

**Issue by dpiliouras** [duct-framework/migrator.ragtime#14]
I'm using the dummy up/down (foo) migrations to test-drive this library, and I would expect that the `up` part is executed on system-init (e.g. per `go`), and the `down` part on system-shutdown (e.g. per `halt`). However, I am only seeing the `up` bit executed - not the `down` bit (i.e. the `foo` table survives halting the system). Is this to be expected? Here is my config, in case it helps:

```clj
  :duct.migrator.ragtime/resources {:path "db/sql/migrations"}
  :duct.migrator/ragtime
  {:database #ig/ref :duct.database.sql/hikaricp
   :strategy :raise-error
   :migrations [#ig/ref :duct.migrator.ragtime/resources]
   }
```
The `db/sql/migrations` directory simply contains  the two files as shown in the README - i.e. `foo.up.sql` and `foo.down.sql`.

Many thanks in advance

**Comment by dpiliouras** [comment]
Ok, i think I've made some progress, so here is a more relevant question. 

Is the rollback sql (i.e. the `.down.sql` file) only relevant when the `ragtime.strategy/rebase` strategy is being used?

**Comment by weavejester** [comment]
>  I would expect that the `up` part is executed on system-init (e.g. per `go`), and the down part on system-shutdown (e.g. per `halt`).

I'm afraid your expectation is wrong. Only the `up` part is executed, as most of the time shutting down a system should not also delete the database.

**Comment by dpiliouras** [comment]
> as most of the time shutting down a system should not also delete the database

I couldn't agree more , but I'm trying to understand what is the point of providing the `down` part (in the context of `duct`). The only mention of auto-rollbacks I was able to find is [here](https://github.com/weavejester/ragtime/wiki/Concepts#strategies), and more specifically for `ragtime.strategy/rebase`.

**Comment by weavejester** [comment]
You can design migrations that only go one way. The reason why you might want to add migrations that revert as well is that you can manually trigger them to roll back a database upgrade that didn't work out correctly.

They are also useful, as you found out, when combined with the rebase strategy, which is the default in development environments. If you change a migration in development and reset the system, it will roll back the existing migrations up to the point of change, then reapply the new version.

**Comment by dpiliouras** [comment]
Right, i think I get it now - thanks again 👍
