### ISSUE TITLE
How to use SQL files base migrations

### ISSUE THREAD

**Issue by michalvalasek** [duct-framework/migrator.ragtime#2]
Hello James!

Would it be possible to add a simple example of how to use SQL file based migrations to the README file? I'm trying to figure this out on my own (no luck yet) and such example would be a great help for me (and I dare to guess there will be other people in similar situation). Thanks!

**Comment by weavejester** [comment]
Sure. As the README says, the `:up` and `:down` keys can be resources, so just set the values to `#duct/resource "foo/migrations/bar.sql"`, or whatever the resource path to your migration is. I'll add a proper example to the README.

**Comment by michalvalasek** [comment]
Thanks, that would be awesome!

By the way - is there any way to just point ragtime to a directory with SQL migration files - i.e. not give it vector if individual migration files (`#duct/resource`s)?

**Comment by weavejester** [comment]
That's planned, but not implemented yet, I'm afraid.

**Comment by michalvalasek** [comment]
Thanks for the information!

**Comment by mariusz-jachimowicz-83** [comment]
@michalvalasek you can use my module for it https://github.com/mariusz-jachimowicz-83/duct-migrations-auto-cfg
